#!/bin/bash

usage() {
	echo "usage: git diffview [<path> [<path>]]"
}

main() {
    case $# in
        0) from="HEAD~"; to="HEAD" ;;
        1) if [ $1 == "-h" ] ; then
               usage; exit 0
           fi
           from=$1; to="HEAD" ;;
        2) from=$1; to=$2 ;;
        *) usage; exit 1;;
    esac

    temp_dir=$(mktemp -d)

    git diff --name-status $from $to | {
        while read name ; do
            status=$(echo "$name" | awk '{print $1}')
            filename=$(echo "$name" | awk '{$1=""; sub(/^  */,"", $0); print }')

            mkdir -p "$temp_dir/$filename $status"
        done
    }

    cd $temp_dir
    tree --noreport *
    cd - > /dev/null
    rm -rf $temp_dir

    exit 0
}

main "$@"

